'''
    You will only be writing code in this file and this is the only file submitted to the autograder.
'''


def get_version():
    '''
        print the version of python that you are using.
    '''
    "*** WRITE YOUR CODE HERE ***"
    import platform
    return platform.python_version()


def alternative_sum(start, n):
    '''
        modify the function to return a list with generated by an alternative sum sequence explained in the assignment handout
    '''
    "*** WRITE YOUR CODE HERE ***"
    if start < 0 or n not in range(5, 21):
        return []

    result = [start]
    for _ in range(n-1):
        if len(result) < 3:
            result.append(result[-1] + result[-1])
        else:
            result.append(result[-1] + result[-3])
    return result


def order_scores():
    '''
        read the files scores.csv in the data directory and return the list of names sorted in ascending order of the scores.
    '''
    "*** WRITE YOUR CODE HERE ***"
    with open('./data/scores.csv', 'r') as f:
        f.readline()
        names, scores = [], []
        for line in f:
            n, s = line.strip().split(',')
            names.append(n)
            scores.append(s)

        return [n for _, n in sorted(zip(scores, names))]
